spring.application.name=aplorax-backend

#banco de dados data: 28/06/2026

spring.datasource.url=jdbc:postgresql://localhost:5432/aplorax_db
spring.datasource.username=postgres
spring.datasource.password=adm2145
spring.datasource.driver-class-name=org.postgresql.Driver


#JPA de arthurzinho data: 28/06/2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#porta do servidor
server.port=8080